name: Site Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: 15 */6 * * 0,1,2,5,6
    - cron: 15 * * * 3,4

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
    # - run: npm run build
    # - run: git diff
    - name: Deploy gh-pages branch
      run: |
        git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        npm run deploy -- -u "Reposiing GitHub Actions <actions@reposing.net>"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
